nypublicradio/pattern-lab

source/scss/_library/_base.forms.scss
source/scss/_library/_module.article.scss
source/scss/_library/_module.header.scss
source/scss/_library/_objects.icons.scss
source/scss/_library/_objects.navs.scss
source/scss/_library/_objects.text.scss
source/scss/_library/_objects.touts.scss
source/scss/themes/default/_theme.fonts.scss
source/scss/themes/default/_theme.variables.scss

- combine google fonts into single import statement
- rework spacing to be based on multiples of 8
- get rid of `$pad` vars

spacing and google fonts

---

source/scss/_library/_base.lists.scss
source/scss/_library/_objects.blocks.scss
source/scss/_library/_objects.cards.scss
source/scss/_library/_objects.lists.scss
source/scss/_library/_objects.text.scss
source/scss/themes/default/_theme.mixins.scss

replace rems with raw pixels

---

source/scss/_library/_generic.reset.scss
source/scss/_library/_module.header.scss
source/scss/_library/_objects.lists.scss
source/scss/_library/_tools.mq-tests.scss
source/scss/themes/default/_theme.variables.scss

just some general clean up I noticed that didn't belong in a feature PR

some tweaks

---

source/_patterns/02-molecules/article/figure.json
source/scss/_library/_objects.leads.scss
source/scss/_library/_objects.media.scss
source/scss/_library/_objects.text.scss

would you mind taking a peek at a few of these changes? nothing major. some small bits of clean up and a couple targeted rules to help with ember compatibility.

few tweaks for ember compat

---

source/_patterns/02-molecules/meta/header-article-meta.twig
source/_patterns/02-molecules/meta/header-meta.twig
source/_patterns/03-organisms/global/header.twig
source/scss/_library/_config.imports.scss
source/scss/_library/_module.article.scss
source/scss/_library/_module.header.scss
source/scss/_library/_objects.buttons.scss
source/scss/_library/_objects.components.scss
source/scss/_library/_objects.forms.scss
source/scss/_library/_objects.navs.scss
source/scss/_library/_objects.touts.scss
source/scss/_library/_settings.z-index.scss
source/scss/_library/_tools.mq-tests.scss

I added a z-index manifest because I was having some issues controlling the z-index with the fly out and the side menu.
also I found moving the side menu into `header.twig` didn't hurt anything.

a few more compatibility updates

---

source/scss/_library/_module.header.scss
source/scss/_library/_objects.navs.scss

Most of these commits were made to reduce the depth of applicability and override some styles added by the documentation library I'm using.

some more compatibility

---

config/config.yml
source/_layouts/main.twig
source/_patterns/01-atoms/text/kicker.twig
source/_patterns/02-molecules/blocks/block.twig
source/_patterns/02-molecules/text/back-to-top.twig
source/_patterns/03-organisms/global/header.twig
source/_patterns/04-templates/article.twig
source/_patterns/04-templates/home.json
source/_patterns/04-templates/home.twig
source/js/script.js
source/scss/_library/_modifier.animations.scss
source/scss/_library/_module.header.scss
source/scss/_library/_objects.blocks.scss
source/scss/_library/_objects.forms.scss
source/scss/_library/_objects.sections.scss
source/scss/_library/_objects.text.scss
source/scss/_library/_objects.touts.scss
source/scss/themes/default/_theme.overrides.scss

https://jira.wnyc.org/browse/DS-97

Addressing homepage (and some global) feedback

---

source/scss/_library/_base.media.scss

thoughts? this seems to allow image to scale in both directions

allow images to preserve ratios when scaling down

---

source/scss/_library/_objects.media.scss

gallery lead current images should be clickable

---

source/_data/data.json

Changing the blockquote to be a real quote about NYC

---

source/scss/_library/_objects.text.scss

allowing this to be inline doesn't seem to affect the layout after the other updates we've made. LMK what you think?

let these be inline so they can wrap

---

source/scss/_library/_objects.text.scss

apply the same styles to the container so any raw text nodes get body styles
for [DS-132]

text from the database is broken and gets parsed outisde of a p tag

---

source/scss/_library/_objects.text.scss

[DS-158](https://jira.wnyc.org/browse/DS-158)

add sponsored modifier to kicker

---

source/scss/_library/_objects.leads.scss
source/scss/_library/_objects.media.scss

is this the right place for this kind of thing?

make a more generic image ratio helper

---

source/_patterns/04-templates/section.twig
source/_patterns/04-templates/tag.twig

Add aria-hidden to the hr tags so that Voiceover does not announce them

Accessible hr tags

---

source/scss/_library/_objects.media.scss

and give ratio'd images a background fill

make image ratios a bit more extensible

---

source/_patterns/03-organisms/gallery/gallery-overlay.json
source/scss/_library/_objects.text.scss

The preexisting image credit was hard to read, not accessible, and didn't have an underline/hover state. Also added it to the JSON data

Improving link visibility in Gallery Img Credits

---

source/scss/themes/default/_theme.variables.scss

per https://jira.wnyc.org/browse/DT-77

update reddish orange from #f25917 to #de5e36

---

source/scss/themes/default/_theme.variables.scss

https://jira.wnyc.org/browse/DT-77

Update fireengine-red to WNYC-fireengine-red

---

source/_patterns/03-organisms/touts/contact.twig
source/scss/_library/_objects.media.scss
source/scss/_library/_objects.touts.scss
source/scss/_library/_trumps.helper-classes.scss

Removing black borders on images

---

source/_data/data.json
source/_patterns/02-molecules/navigation/breadcrumb.twig
source/_patterns/03-organisms/article/article-header.twig
source/_patterns/05-pages/article/article~sponsored.json
source/scss/_library/_module.main.scss
source/scss/_library/_objects.navs.scss
source/scss/_library/_objects.text.scss
source/scss/themes/default/_theme.variables.scss

https://jira.wnyc.org/browse/DS-423

Adding sponsored version of article.

---

source/_patterns/02-molecules/ad-units/sponsored.json
source/_patterns/02-molecules/ad-units/sponsored.twig
source/_patterns/02-molecules/text/byline.twig
source/_patterns/03-organisms/article/article-body.twig
source/_patterns/03-organisms/article/article-header.twig
source/_patterns/05-pages/article/article~contributors.json
source/scss/_library/_module.main.scss

https://jira.wnyc.org/browse/CMS-717

Adding new sponsor section.

---

source/scss/_library/_objects.blocks.scss
source/scss/_library/_objects.sections.scss

https://jira.wnyc.org/browse/CMS-677

Updating breaking news banner styles. - CMS-677

---

source/scss/_library/_module.gallery.scss
source/scss/_library/_objects.text.scss

https://jira.wnyc.org/browse/DS-423
https://jira.wnyc.org/browse/CMS-670

Mobile bugs that were causing overflow

---

source/_data/data.json
source/_patterns/03-organisms/gallery/gallery-overlay.json
source/_patterns/03-organisms/gallery/gallery-overlay.twig
source/_patterns/05-pages/article/article~gallery-long.json
source/_patterns/05-pages/article/article~gallery.json
source/scss/_library/_module.gallery.scss
source/scss/_library/_objects.text.scss

https://jira.wnyc.org/browse/DS-455

Updating ad placement logic per length for gallery overlay

---

source/scss/_library/_module.gallery.scss

https://jira.wnyc.org/browse/CMS-799 
Add ad label text color exception for gallery

CMS-799 Add ad label text color exception for gallery

---

source/scss/_library/_objects.forms.scss

Hey Seori - Laura had some more design tweaks to this if you don't mind :)

DS-590 article newsletter signup form design tweaks
