source/_patterns/02-molecules/blocks/block-list-item.json, source/_patterns/02-molecules/blocks/block-list-item.twig, source/_patterns/02-molecules/blocks/block.json, source/_patterns/02-molecules/blocks/block.twig, source/scss/_library/_objects.blocks.scss
The content inside the `block.twig` component is default block content and both sections (`block_media` and `block_object`) can be completely rewritten if extended in another pattern. In this instance, `block-list-item.twig` can reuse those default elements. In more complex instances, we'll likely be injecting other components and other necessary elements.
=> Refactoring main block component to match ember's media object component

source/_patterns/02-molecules/leads/lead-gallery.twig, source/_patterns/02-molecules/leads/lead.twig, source/_patterns/02-molecules/leads/lead~gallery.json, source/_patterns/03-organisms/article/article-header.twig, source/scss/_library/_base.media.scss, source/scss/_library/_config.imports.scss, source/scss/_library/_module.article.scss, source/scss/_library/_objects.leads.scss, source/scss/_library/_objects.media.scss
two thing I tried to do here: 
1. use the existing `figure-with-caption` molecule in both the `lead` and `lead-gallery` molecules
2. update the `figure-with-caption` molecule with parent classes for the different contexts
Note this adds a new `lead-gallery` molecule in place of the `lead~gallery` pseudopattern.
=> Refactor lead to re use figure with caption

source/_patterns/02-molecules/social/share-tools.twig, source/_patterns/02-molecules/social/share-tools~vertical.json, source/_patterns/03-organisms/global/footer.twig, source/_patterns/03-organisms/global/side-menu.twig, source/js/script.js, source/scss/_library/_module.article.scss, source/scss/_library/_module.footer.scss, source/scss/_library/_module.header.scss, source/scss/_library/_objects.components.scss, source/scss/_library/_objects.icons.scss
Visually, these two molecules are very similar, and the behavior can be easily controlled via developer usage in ember.
I was able to reduce the amount of contextual rules by setting up some sane defaults for responsive styles.
The vertical orientation is controlled via a class, and there's a small media query listener that will run on templates that have an article header organism present.
=> merge `social-links` into `share-tools`

source/scss/_library/_objects.forms.scss
It ends up peeking through the gallery overlay on my end.
=> why does the form field group have such a high z index?

source/scss/_library/_objects.sections.scss
there's a slimmed down header we're using for the initial site search results:
https://app.zeplin.io/project/5a9dc653aaaa927d5696de7c/screen/5cc89f2b7a40b8038f29c587
and
https://app.zeplin.io/project/5a9dc653aaaa927d5696de7c/screen/5cc89f2b70cbdf6850fd6bca
=> a couple extra classes for initial site search results

source/scss/_library/_objects.components.scss
there's no font-size actually applied to this element
=> explicitly size this

source/_patterns/03-organisms/sections/block-list-group-1col-with-heading-block.twig, source/_patterns/03-organisms/sections/block-list-group-with-300x600-ad.twig, source/_patterns/03-organisms/sections/block-list-group-with-ad.twig, source/_patterns/03-organisms/sections/block-list-group-with-footer-block-and-ad.twig, source/_patterns/03-organisms/touts/recirculation.twig, source/scss/_library/_objects.sections.scss
Looking at the CSS, the rules for the `c-recirc-tout` block have a lot of overlap with the `c-block-group` block, so I'd like to make it a modifier.
It'll make the code easier to maintain on my end and arguably easier to reason about if we have a single block layout organism that has multiple variations that can be configured with a single class modifier.
=> Make recirc-tout a block-group modifier

source/scss/_library/_objects.leads.scss
I'd prefer to use `object-fit: contain`, but... IE
[ticket](https://jira.wnyc.org/browse/DS-166)
=> force images to resize within a 3:2 aspect ratio

source/_patterns/02-molecules/meta/header-article-meta.twig, source/scss/_library/_module.header.scss
article templates already have an `h1` in the article header organism,
and there should only bre one h1 on a page.
I made this update on the website, but I want pattern lab in sync. Plus
the letter spacing rule is inherited from h1, and needs to be expclitly
set on this element now.
[ticket](https://jira.wnyc.org/browse/DS-77)
=> make this heading semantically meaningless

source/scss/_library/_objects.forms.scss
[DS-240]
I know this seems nit picky, but I want this component to be agnostic of its context. As it is there's already some expectations embedded in the code that it should always be in the upper right of the page.
In the ember app, I've attempted to nudge this towards being less contextually sensitive by using the more generic `.is-open` class, instead of the `.top-search-is-active` class. I see that you're using data attributes to toggle some DOM state, which is a bit limited when it comes to generic state handlers, so I didn't want to open up a big refactor of the JS utils you're using.
For now, we can have some duplicate rules, but at some point I'd like to revisit certain components so class names and CSS rules don't specify things like page position.
=> sarch icon fill color

source/scss/themes/default/_theme.overrides.scss
in the app, there's only 1 header element, so add this `:not` selector 
to scope the offset stylings to only when the header is in the initial 
state
=> add'l scope for homepage header style

source/_data/data.json, source/scss/_library/_module.main.scss
Update billboard to support mobile leaderboard ad size (320x50)
When this was 300, 320x50 ads would get 20 pixels cut off of the sides
=> Update billboard to support mobile leaderboard ad size (320x50)

source/_patterns/02-molecules/banners/box-banner.json, source/_patterns/02-molecules/banners/box-banner.twig, source/_patterns/02-molecules/banners/box-banner~title-only.json, source/_patterns/02-molecules/banners/text-banner.json, source/_patterns/02-molecules/banners/text-banner.twig, source/_patterns/02-molecules/blocks/block.twig, source/_patterns/02-molecules/blocks/urgent-block.json, source/_patterns/02-molecules/blocks/urgent-block.twig, source/scss/_library/_base.links.scss, source/scss/_library/_objects.blocks.scss, source/scss/_library/_objects.messaging.scss
I refactored the `box-banner` and `text-banner` molecules. Please take a moment to read through my commits and give me your thoughts.
`box-banner`
the main changes here were to remove relying on special classes for the desired UI. I'd like to make it so that end-users don't need to remember to include classes for certain styling.
`text-banner`
This was more of an overhaul. In my eyes that the contents of the `text-banner` as they've been designed are essentially a variation on the existing `block` molecule. I made some edits to `block` so it could be extended with a few simple arguments and refactored the `text-banner` to use these variations, which I'm encapsulating under the name `urgent-block`, based on the fact that the font is red, which implies urgency.
Also there's a commit in here …
=> some banner suggestions

source/scss/_library/_module.gallery.scss
when images are loading, if this isn't set to `initial`, the images will
collapse to zero height. I need their height to be consistent at load so
I can take some measurements for things lik the progress bar and
background.
part of [DS-310](https://jira.wnyc.org/browse/DS-310)
=> reset the image height to `initial`

source/_patterns/02-molecules/blocks/author-block.twig, source/scss/_library/_objects.blocks.scss, source/scss/themes/default/_theme.mixins.scss
put the `dot-divider` in `c-author-block__details` because it's an optional element, and my hunch is that the dot should only be displayed if there's content on both sides.
when an author (or staff member) doesn't have articles (e.g. ad sales people), there's no "articles" link shown.
[DS-327](https://jira.wnyc.org/browse/DS-327)
=> minor author block tweak

source/_patterns/02-molecules/banners/box-banner.twig
I can imagine a world where we render this box without including a close
button, so I added this class to the title so that the spacing is
maintained, even if the lobotomized owl selector chain is broken with
the absence of the close button.
=> make sure the title has spacing

source/scss/_library/_module.gallery.scss, source/scss/_library/_objects.text.scss
Removed style changes for Gallery Overlay credit links from source/scss/_library/_objects.text.scss
And moved them to source/scss/_library/_module.gallery.scss so they do not affect the credit links on other article pages
=> Moving o-credit style fixes to the Gallery Overlay

source/scss/_library/_objects.blocks.scss
for the breaking news banner (and possibly other uses of the block).
The line height for this is inherited from way up on the `body` tag. Wondering if you wouldn't mind scoping this down a bit; I'm getting conflicts on the ember side when displaying the component in a non-gothamist context.
=> scope in this line height a bit

source/scss/_library/_objects.leads.scss, source/scss/_library/_objects.text.scss
Hey @tpitre, I was seeing some discrepencies in article templates w/r/t how images are treated in the lead asset position vs embedded in an article. The mark up on pattern lab is different for the two positions, but we're going to have the same mark up in the app b/c they're pulling from the same component.
I also saw some differences in the image caption styles when compared to zeplin. I think this PR should resolve those issues, and hopefully overcome the markup differences as well.
=> image caption styles

source/scss/_library/_objects.text.scss, source/scss/_library/_settings.z-index.scss
Closes [DS-421](https://jira.wnyc.org/browse/DS-421)
=> Adding z-index to back to top to appear above takeover ads. 

source/_patterns/04-templates/home.twig, source/scss/_library/_objects.sections.scss
Refactor to move banners out of home page content area, so we can put these banners on all pages more easily.  This shouldn't change existing spacing on the home page.
Also renamed the `.c-home__sections` blocks to individual sections (`content-top,tout,content-bottom`) since they all had different rules and don't really feel like similar kinds of things.
https://jira.wnyc.org/browse/CMS-583
=> CMS-583 Refactor to move banners out of home page content area
